#!/usr/bin/env python3
"""
GitHub Copilot Agent Setup Script
Installs multi-agent configuration for GitHub Copilot in VS Code.
"""

import os
import json
import shutil
from pathlib import Path
from datetime import datetime


class CopilotAgentSetup:
    """Install GitHub Copilot agent configuration."""

    def __init__(self, repo_path: str):
        self.repo_path = Path(repo_path).resolve()
        self.analysis_path = self.repo_path / ".copilot/analysis.json"
        self.analysis = self._load_analysis()

    def _load_analysis(self) -> dict:
        """Load project analysis."""
        if not self.analysis_path.exists():
            print("⚠️  No analysis found. Run analyze_project.py first.")
            return {}

        with open(self.analysis_path) as f:
            return json.load(f)

    def run(self):
        """Execute setup process."""
        print("🚀 GitHub Copilot Agent Setup")
        print("="*50)

        steps = [
            ("Creating directory structure", self.create_directories),
            ("Installing Copilot configuration", self.install_copilot_config),
            ("Creating project prompts", self.create_prompts_file),
            ("Configuring VS Code settings", self.configure_vscode),
            ("Updating .gitignore", self.update_gitignore),
        ]

        for step_name, step_func in steps:
            print(f"\n📍 {step_name}...")
            try:
                step_func()
                print(f"   ✅ {step_name} complete")
            except Exception as e:
                print(f"   ❌ {step_name} failed: {e}")

        print("\n" + "="*50)
        print("✨ Setup Complete!")
        print("\nNext steps:")
        print("1. Open VS Code")
        print("2. Install GitHub Copilot extension")
        print("3. Open Copilot Chat and paste master prompt from .github/copilot/prompts.md")
        print("4. Start coding with agent-guided suggestions!")

    def create_directories(self):
        """Create required directories."""
        directories = [
            ".github/copilot",
            ".vscode",
            ".copilot"
        ]

        for dir_path in directories:
            (self.repo_path / dir_path).mkdir(parents=True, exist_ok=True)

    def install_copilot_config(self):
        """Install GitHub Copilot config.yml."""
        config_path = self.repo_path / ".github/copilot/config.yml"

        # Get recommended agents from analysis
        recommended = self.analysis.get("recommended_agents", {})
        core_agents = recommended.get("core", [])
        optional_agents = recommended.get("optional", [])
        all_agents = core_agents + optional_agents

        # Build config
        config = self._build_config(all_agents)

        with open(config_path, 'w') as f:
            f.write(config)

    def _build_config(self, agents: list) -> str:
        """Build Copilot config YAML."""
        config = """# GitHub Copilot Multi-Agent Configuration
# Generated by Superior Copilot Agent Setup
# Version: 1.0

version: 1

agents:
  enabled: true
  enforce_standards: true

  ownership:
"""

        # Add agent configurations based on detected agents
        agent_configs = {
            "Security Agent": {
                "paths": ["**/*"],
                "standards": [
                    "No hardcoded secrets",
                    "Validate all inputs",
                    "Use parameterized queries",
                    "Implement rate limiting"
                ]
            },
            "Logic Agent": {
                "paths": ["**/*.py", "**/*.js", "**/*.ts", "**/*.go"],
                "standards": [
                    "Handle all edge cases",
                    "Validate business logic",
                    "Use meaningful variable names",
                    "Include error handling"
                ]
            },
            "Test Agent": {
                "paths": ["tests/**", "**/test/**", "**/*.test.*"],
                "standards": [
                    "Aim for >80% coverage",
                    "Test edge cases",
                    "Include integration tests",
                    "Mock external dependencies"
                ]
            },
            "Doc Agent": {
                "paths": ["**/*"],
                "standards": [
                    "Keep documentation in sync with code",
                    "Add docstrings to functions",
                    "Update README for new features",
                    "Document API changes"
                ]
            },
            "Data Agent": {
                "paths": ["**/models/**", "**/database/**", "**/schemas/**"],
                "standards": [
                    "Include data validation",
                    "Use type hints",
                    "Add migration reversibility",
                    "Handle data integrity"
                ]
            },
            "Infrastructure Agent": {
                "paths": ["**/infrastructure/**", "**/*.dockerfile", "**/deploy/**"],
                "standards": [
                    "Use infrastructure as code",
                    "Include health checks",
                    "Implement graceful shutdown",
                    "Add resource limits"
                ]
            },
            "Performance Agent": {
                "paths": ["**/api/**", "**/routes/**", "**/handlers/**"],
                "standards": [
                    "Optimize database queries",
                    "Use async where possible",
                    "Add caching for expensive operations",
                    "Monitor response times"
                ]
            },
            "Refactor Agent": {
                "paths": ["**/*.py", "**/*.js", "**/*.ts"],
                "standards": [
                    "Eliminate code duplication",
                    "Extract reusable functions",
                    "Simplify complex logic",
                    "Improve naming clarity"
                ]
            },
            "Observability Agent": {
                "paths": ["**/*"],
                "standards": [
                    "Add structured logging",
                    "Include tracing spans",
                    "Export metrics",
                    "Add health endpoints"
                ]
            },
            "Research Agent": {
                "paths": ["**/*"],
                "standards": [
                    "Check for latest API versions",
                    "Validate deprecated features",
                    "Follow framework best practices",
                    "Use current patterns"
                ]
            },
            "DevEx Agent": {
                "paths": ["**/*"],
                "standards": [
                    "Add helpful code comments",
                    "Include setup instructions",
                    "Provide example usage",
                    "Document common pitfalls"
                ]
            },
            "UX/Accessibility Agent": {
                "paths": ["**/components/**", "**/ui/**", "**/*.jsx", "**/*.tsx"],
                "standards": [
                    "Include ARIA labels",
                    "Support keyboard navigation",
                    "Test color contrast",
                    "Add responsive design"
                ]
            },
            "Error Handling Agent": {
                "paths": ["**/*"],
                "standards": [
                    "Handle all exceptions",
                    "Provide useful error messages",
                    "Log errors with context",
                    "Include recovery paths"
                ]
            },
            "Dependency Agent": {
                "paths": ["package.json", "requirements.txt", "go.mod", "Cargo.toml"],
                "standards": [
                    "Pin dependency versions",
                    "Check for security vulnerabilities",
                    "Remove unused dependencies",
                    "Document dependency purposes"
                ]
            },
            "Build Agent": {
                "paths": [".github/**", ".gitlab-ci.yml", "Jenkinsfile"],
                "standards": [
                    "Cache build dependencies",
                    "Run tests in CI",
                    "Check code quality",
                    "Deploy automatically"
                ]
            },
            "Cost Optimization Agent": {
                "paths": ["**/cloud/**", "**/lambda/**", "serverless.yml"],
                "standards": [
                    "Optimize resource allocation",
                    "Use cost-effective services",
                    "Implement auto-scaling",
                    "Monitor spending"
                ]
            },
            "Knowledge Agent": {
                "paths": ["docs/**", "wiki/**", "**/*.md"],
                "standards": [
                    "Keep docs up to date",
                    "Add architecture diagrams",
                    "Document decisions",
                    "Maintain changelog"
                ]
            },
            "Ethics & Compliance Agent": {
                "paths": ["**/*"],
                "standards": [
                    "Follow data privacy regulations",
                    "Implement consent management",
                    "Audit data access",
                    "Document compliance"
                ]
            },
            "Benchmark Agent": {
                "paths": ["**/benchmark/**", "**/perf/**"],
                "standards": [
                    "Add performance benchmarks",
                    "Track performance trends",
                    "Test at scale",
                    "Profile critical paths"
                ]
            },
            "Security Red Team Agent": {
                "paths": ["**/api/**", "**/routes/**", "**/public/**"],
                "standards": [
                    "Test for vulnerabilities",
                    "Validate authentication",
                    "Check authorization",
                    "Test input fuzzing"
                ]
            }
        }

        for agent in agents:
            if agent in agent_configs:
                cfg = agent_configs[agent]
                config += f"""
    - agent: "{agent}"
      paths:
"""
                for path in cfg["paths"]:
                    config += f'        - "{path}"\n'

                config += "      standards:\n"
                for standard in cfg["standards"]:
                    config += f'        - "{standard}"\n'

        # Add quality settings
        config += """
quality:
  test_coverage_required: true
  type_hints_required: true
  docstrings_required: true

suggestions:
  max_lines: 20
  include_tests: true
  include_types: true
  include_docs: true

security:
  block:
    hardcoded_passwords: true
    api_keys_in_code: true
    sql_injection_risk: true
"""

        return config

    def create_prompts_file(self):
        """Create prompts.md with project context."""
        prompts_path = self.repo_path / ".github/copilot/prompts.md"

        languages = ", ".join(self.analysis.get("languages", {}).keys())
        frameworks = ", ".join(self.analysis.get("frameworks", []))
        agents = self.analysis.get("recommended_agents", {})
        core_agents = ", ".join(agents.get("core", []))
        optional_agents = ", ".join(agents.get("optional", []))

        content = f"""# GitHub Copilot Project Context

**Project:** {self.repo_path.name}
**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Master Prompt for Copilot Chat

Copy and paste this into a new Copilot Chat window when starting a session:

```
You are an AI assistant orchestrating a multi-agent system for code quality.

Project: {self.repo_path.name}
Tech Stack: {languages}
Frameworks: {frameworks or 'None detected'}

Enabled Agents:
- Core: {core_agents}
- Optional: {optional_agents or 'None'}

Each agent is an expert reviewer with specific responsibilities:

Core Agents (Always Active):
- Security Agent: Prevents vulnerabilities, secrets, injection attacks
- Logic Agent: Ensures correctness, handles edge cases, validates business logic
- Test Agent: Enforces testing standards and >80% coverage
- Doc Agent: Maintains documentation sync with code
- Data Agent: Validates data integrity, schemas, and migrations
- Infrastructure Agent: Reviews deployment, containers, and infrastructure code

Optional Agents (Auto-Enabled):
- Performance Agent: Optimizes algorithms, queries, response times, caching
- Refactor Agent: Eliminates duplication, improves code clarity
- Observability Agent: Adds logging, tracing, metrics, monitoring
- Research Agent: Validates latest APIs, checks for deprecated features
- DevEx Agent: Improves developer experience, documentation, setup
- UX/Accessibility Agent: Ensures accessibility, responsive design, ARIA labels
- Error Handling Agent: Comprehensive exception handling, recovery paths
- Dependency Agent: Manages dependencies, versions, security updates
- Build Agent: Optimizes CI/CD, caching, deployment automation
- Cost Optimization Agent: Reduces cloud costs, optimizes resource usage
- Knowledge Agent: Maintains architecture docs, decisions, changelog
- Ethics & Compliance Agent: GDPR, HIPAA, privacy, data protection
- Benchmark Agent: Performance testing, profiling, optimization
- Security Red Team Agent: Penetration testing, vulnerability scanning

Review all code suggestions through these agents before presenting them to the user.
Only suggest code that passes all agent checks.
If any agent objects, revise the code to address concerns.

For every suggestion:
1. Review with each agent
2. Report any issues found
3. Propose fixes that satisfy all agents
4. Present code with unanimous approval
```

## Project Context

### Architecture
[Add your architecture description here]

### Design Patterns
[Add your design patterns and conventions here]

### Constraints
[Add your technical constraints here]

## Required Standards

### All Functions
- ✅ Type hints for parameters and returns
- ✅ Docstring with description, args, returns, examples
- ✅ Unit tests with ≥80% coverage
- ✅ Error handling for edge cases

### Security
- ✅ No hardcoded secrets (use environment variables)
- ✅ Input validation on all user data
- ✅ Parameterized queries (no string concatenation)
- ✅ Rate limiting on public endpoints

### Performance
- ✅ Async operations for I/O
- ✅ Database query optimization
- ✅ Caching for expensive computations
- ✅ Resource cleanup (context managers)

### Documentation
- ✅ README updated with new features
- ✅ API documentation for endpoints
- ✅ Changelog entries for changes
- ✅ Code comments for complex logic

## Agent Responsibilities

### Security Agent
- **Paths:** All files
- **Focus:** Vulnerabilities, secrets, injection attacks
- **Veto:** Hardcoded secrets, SQL injection, XSS vulnerabilities

### Logic Agent
- **Paths:** Source code files
- **Focus:** Correctness, edge cases, business logic
- **Veto:** Unhandled exceptions, logic errors, missing validation

### Test Agent
- **Paths:** Test files and source files
- **Focus:** Test coverage, quality, regression prevention
- **Veto:** Coverage <80%, missing critical tests, flaky tests

### Performance Agent
- **Paths:** API routes, handlers, data processing
- **Focus:** Efficiency, scalability, response times
- **Veto:** O(n²) algorithms, N+1 queries, blocking I/O

### Data Agent
- **Paths:** Models, schemas, migrations
- **Focus:** Data validation, integrity, schema design
- **Veto:** Missing validation, schema violations, data corruption risk

### Doc Agent
- **Paths:** Documentation and source code
- **Focus:** Documentation sync, completeness, clarity
- **Veto:** Missing docs, outdated information, broken references

---

## Usage Tips

1. **Start sessions with context:** Paste the master prompt into Copilot Chat
2. **Ask for multi-agent review:** "Review this from all agent perspectives"
3. **Use slash commands:** /explain, /tests, /doc, /fix
4. **Keep relevant files open:** Copilot uses context from open tabs
5. **Iterate on prompts:** Update this file as you discover patterns

---

**For more information:** See ~/agentic-setup/agentic_setup/github-copilot/README.md
"""

        with open(prompts_path, 'w') as f:
            f.write(content)

    def configure_vscode(self):
        """Configure VS Code settings."""
        settings_path = self.repo_path / ".vscode/settings.json"

        settings = {
            "github.copilot.enable": {
                "*": True,
                "yaml": True,
                "markdown": True,
                "json": True,
                "dockerfile": True
            },
            "github.copilot.advanced": {
                "debug.overrideEngine": "gpt-4",
                "contextWindow": 8000
            },
            "editor.inlineSuggest.enabled": True,
            "github.copilot.editor.enableAutoCompletions": True
        }

        with open(settings_path, 'w') as f:
            json.dump(settings, f, indent=2)

    def update_gitignore(self):
        """Add Copilot files to .gitignore."""
        gitignore_path = self.repo_path / ".gitignore"

        entries = """
# GitHub Copilot Agent Configuration (User-Specific)
# Each developer configures their own Copilot agents
.copilot/
.vscode/copilot-settings.json
"""

        if gitignore_path.exists():
            with open(gitignore_path) as f:
                existing = f.read()

            if ".copilot/" not in existing:
                with open(gitignore_path, 'a') as f:
                    f.write(entries)
        else:
            with open(gitignore_path, 'w') as f:
                f.write(entries)


def main():
    """CLI entry point."""
    import sys

    if len(sys.argv) < 2:
        print("Usage: python setup_copilot_agents.py <repo_path>")
        sys.exit(1)

    repo_path = sys.argv[1]
    setup = CopilotAgentSetup(repo_path)
    setup.run()


if __name__ == "__main__":
    main()
